{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-imager
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/imager_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/imager/imager_{{ version }}.tar.gz
  sha256: 66919076fcc1211b1da4e20d934037c420c63c8a098c0b322cf3e398d3c20455

build:
  skip: true  # [not linux]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}            # [not win]
    - {{ stdlib("c") }}              # [not win]
    - {{ compiler('m2w64_c') }}      # [win]
    - {{ stdlib("c") }}              # [win]
    - {{ compiler('cxx') }}          # [not win]
    - {{ compiler('m2w64_cxx') }}    # [win]
    - {{ posix }}filesystem          # [win]
    - {{ posix }}sed                 # [win]
    - {{ posix }}grep                # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake            # [not win]
    - {{ posix }}automake-wrapper    # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils           # [win]
    - {{ posix }}zip                 # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - xorg-libxfixes  # [linux]
  host:
    - r-base
    - r-downloader
    - r-igraph
    - r-jpeg
    - r-magrittr
    - r-png
    - r-purrr
    - r-readbitmap
    - r-rcpp >=0.11.5
    - r-stringr
    - libtiff
    - fftw
    - xorg-libx11  # [linux]
  run:
    - r-base
    - r-downloader
    - r-igraph
    - r-jpeg
    - r-magrittr
    - r-png
    - r-purrr
    - r-readbitmap
    - r-rcpp >=0.11.5
    - r-stringr
    - xorg-libx11  # [linux]

test:
  commands:
    - 'LD_LIBRARY_PATH="${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib" $R -e "library(''imager'')"'  # [not win]
    - "\"%R%\" -e \"library('imager')\""  # [win]

about:
  home: https://dahtah.github.io/imager
  dev_url: https://github.com/dahtah/imager
  doc_url: https://dahtah.github.io/imager/imager.html
  license: LGPL-3.0-only
  summary: Fast image processing for images in up to 4 dimensions (two spatial dimensions, one time/depth dimension, one colour dimension). Provides most traditional image processing tools (filtering, morphology, transformations, etc.) as well as various functions for easily analysing image data using R. The package wraps
    'CImg', <http://cimg.eu>, a simple, modern C++ library for image processing.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
